language: python
python:
  - "3.8"

services:
  - docker

before_script: 
  - touch .env
  - echo DEBUG=${DEBUG} >> .env
  - echo SECRET_KEY=${SECRET_KEY} >> .env
  - echo BASE_URL=${BASE_URL} >> .env
  - echo DATABASE_URL=${DATABASE_URL} >> .env
  - pip install docker-compose

script:
  - docker-compose run ressonantes_app sh -c "python manage.py test && flake8"