language: python
python:
  - "3.8"

env:
  global:
    - DEBUG=True
    - SECRET_KEY=^@%h28h9wit$ous5j^3%rq-4j%*!t^#2-d4pbvzkdxkz%edg64
    - DATABASE_URL=psql://postgres:K8YvzabSrzeGUAecJ8hQkfuXZEjU9ZcY@ressonantes_db/db_ressonantes_app
    - BASE_URL=http://localhost:8000/

services:
  - docker

before_script: 
  - touch /ressonantes/ressonantes/settings/.env
  - echo DEBUG=$DEBUG >> .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo BASE_URL=$BASE_URL >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - pip install docker-compose

script:
  - docker-compose run ressonantes_app sh -c "python manage.py test && flake8"