language: python
python:
  - "3.8"

env:
  - DEFAULT_FROM_EMAIL=castro@webappsagency.com.br
  - BASE_URL=http://www.ressonantes.com

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run ressonantes_app sh -c "ENV_PATH=.test.env python manage.py test && flake8"