language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run ressonantes_app sh -c "ENV_PATH=.test.env python manage.py test && flake8"