# Generated by Django 2.2.15 on 2020-08-28 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Define o e-mail de acesso do usuário', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
    ]
