# Generated by Django 2.2.15 on 2020-09-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities_uf', to='core.Uf', verbose_name='Estado'),
        ),
    ]
